/**
 * Если Firestone отдаёт hero_name по-английски или slug не совпал с библиотекой —
 * показываем русское имя (подписи как в клиенте HS).
 * Ключи: нижний регистр, без лишних пробелов.
 */
export const FIRESTONE_EN_TO_RU: Record<string, string> = {
  'queen azshara': 'Королева Азшара',
  patchwerk: 'Лоскутик',
  'lord jaraxxus': 'Лорд Джараксус',
  'queen wagtoggle': 'Королева Пыхлевих',
  'overlord saurfang': 'Воевода Саурфанг',
  'lady vashj': 'Леди Вайш',
  "dancin' deryl": 'Танцор Дэрил',
  'dancin deryl': 'Танцор Дэрил',
  'ini stormcoil': 'Ини Штормоверть',
  'vanndar stormpike': 'Вандар Баранье Копыто',
  "yogg-saron, hope's end": 'Йогг-Сарон, конец Надежды',
  'yogg-saron': 'Йогг-Сарон',
  "cap'n hoggarr": 'Капитан Дробитель',
  'capn hoggarr': 'Капитан Дробитель',
  'teron gorefiend': 'Терон Кровожад',
  'the lich king': 'Король-лич',
  'millificent manastorm': 'Миллифисент Манашторм',
  'thorim, stormlord': 'Торим, владыка бурь',
  thorim: 'Торим, владыка бурь',
  'inge, the iron hymn': 'Инге Стальной Гимн',
  'inge the iron hymn': 'Инге Стальной Гимн',
  onyxia: 'Ониксия',
  deathwing: 'Смертокрыл',
  morchie: 'Морчи',
  "al'akir": 'Ал\'акир',
  alakir: 'Ал\'акир',
  'illidan stormrage': 'Иллидан Ярость Бури',
  'king mukla': 'Король Мукла',
  sneed: 'Снид',
  'mutanus the devourer': 'Мутанус Пожиратель',
  "n'zoth": 'Н\'Зот',
  nzoth: 'Н\'Зот',
  'murozond, unbounded': 'Мурозонд Бесконечный',
  'murozond unbounded': 'Мурозонд Бесконечный',
  'the great akazamzarak': 'Великий Аказамзарак',
  'tavish stormpike': 'Тавиш Грозовая Вершина',
  tickatus: 'Билетикус',
  rakanishu: 'Раканишу',
  'aranna starseeker': 'Аранна Звездочет',
  artanis: 'Аранна Звездочет',
  "vol'jin": 'Вол\'джин',
  voljin: 'Вол\'джин',
  'a. f. kay': 'А. Ф. Ка',
  'a f kay': 'А. Ф. Ка',
  shudderwock: 'Дрыжеглот',
  'exarch othaar': 'Экзарх Отраар',
  othaar: 'Экзарх Отраар',
};
